# Generated by Django 3.2.12 on 2022-02-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zymo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidstats',
            name='confirmed',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='covidstats',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covidstats',
            name='recovered',
            field=models.BigIntegerField(),
        ),
    ]
